### ISSUE TITLE
switch IRC channel reference from freenode to libera.chat

### ISSUE THREAD

**Issue by pabs3** [libimobiledevice/libimobiledevice.org#3]
The [Community section on the Status page](https://libimobiledevice.org/status/#community) links to freenode. After the implosion of freenode ([1](https://lwn.net/Articles/857140/) [2](https://lwn.net/Articles/856543/)), the folks on the #libimobiledevice IRC channel on freenode have taken the advice of the former staff of freenode (who created the new [libera.chat IRC network](https://libera.chat/)) and moved #libimobiledevice with them to libera.chat. We think that the new channel location should be reflected on the website, please update it.

**Comment by nikias** [comment]
Done, thanks for pointing this out!
