### ISSUE TITLE
Collapsible Elements Won't Open On Site

### ISSUE THREAD

**Issue by tyingq** [libimobiledevice/libimobiledevice.org#4]
All of the collapsible type elements on the site aren't working.  Like the 3-tab widget on the front page with "Connect", "Read", and "Utilities" tabs.   Or the "Download" boxes with the ">" leader on them.

Chrome's dev console says:

```
Uncaught TypeError: Cannot read property 'each' of undefined
    at waypoints.7bfd4c33d7f7fab5ebda017c89eaefac.min.js:7
    at waypoints.7bfd4c33d7f7fab5ebda017c89eaefac.min.js:7
```

It leads to this section of code:

```
   var e = window.jQuery
      , i = window.Waypoint;
    e.each(["innerHeight", "innerWidth", "off", "offset", "on", "outerHeight
```
The "e.each" is the part that's creating the "Cannot read property 'each' of undefined" error.  Probably because jQuery isn't being loaded.

**Comment by tyingq** [comment]
Oh, also this in main page, appears to come from a twig template, and looks suspicious.  Maybe this is where jQuery is supposed to be loaded, but it's loading the main html as javascript instead?

`<script src="https://libimobiledevice.org/"></script>`

**Comment by nikias** [comment]
Guess the github action messed it up... need to find out

**Comment by nikias** [comment]
Thanks for pointing this out. For some reason it fails it too many items are in the asset array. I split it into 2 and now it works. You might have to force-reload the page for it to work.
